name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle wrapper
      run: |
        # Create gradle wrapper if not exists
        if [ ! -d "gradle/wrapper" ]; then
          gradle wrapper --gradle-version 8.6
        fi

    - name: Build debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Get APK info
      run: |
        echo "APK size: $(du -h app/build/outputs/apk/debug/app-debug.apk | cut -f1)"
        echo "APK location: app/build/outputs/apk/debug/app-debug.apk"
